services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        export DS_1_HOST=ds-1
        yarn build && \
        export NODE_ENV=test && \
        yarn test && \
        export NODE_ENV=staging && \
        yarn start
    healthcheck:
      test: "netstat -ltn | grep -c 3000"
  ds-1:
    image: postgres:latest
    ports:
      - "${DS_1_PORT}:5432"
    environment:
      - POSTGRES_USER=${DS_1_USER}
      - POSTGRES_PASSWORD=${DS_1_PASSWORD}
      - POSTGRES_DB=${DS_1_DATABASE}"
