services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command:
      - "yarn build && yarn test && yarn start"
  ds-1:
    image: postgres:latest
    ports:
      - "${DS_1_PORT}:5432"
    environment:
      - POSTGRES_USER=${DS_1_USER}
      - POSTGRES_PASSWORD=${DS_1_PASSWORD}
      - POSTGRES_DB=${DS_1_DATABASE}
